<?php

/**
 * This source code is distributed under the terms as layed out in the
 * GNU General Public License.
 *
 * Purpose: English translation file.
 *
 * @author Sijis Aviles <sijis@users.sourceforge.net>
 * @version $Id$
 * @copyright 2003-2005 Brian A Cheeseman
 **/

$lang['encoding']		= 'iso-8859-1';

// listing options
$lang['file']			= 'File';
$lang['rev']			= 'Rev.';
$lang['age']			= 'Age';
$lang['author']			= 'Author';
$lang['last_log']		= 'Last Lost Entry';

// customization options
$lang['language']		= 'English';
$lang['theme']			= 'Change Theme:';

// quick link bar listing
$lang['change_theme']	= 'Change Theme:';
$lang['change_lang']	= 'Language:';
$lang['up_folder']		= 'Up one folder';
$lang['rev_history']	= 'Revision history for: ';
$lang['code_view']		= 'Code view for: ';
$lang['navigate_to']	= 'Navigate to: ';
$lang['file_ext']		= 'File Extension:';
$lang['mime_type']		= 'Mime Type is:';

// time and date related
$lang['year']			= 'Year';
$lang['years']			= 'Years';
$lang['week']			= 'Week';
$lang['weeks']			= 'Weeks';
$lang['day']			= 'Day';
$lang['days']			= 'Days';
$lang['hour']			= 'Hour';
$lang['hours']			= 'Hours';
$lang['minute']			= 'Minute';
$lang['minutes']		= 'Minutes';
$lang['second']			= 'Second';
$lang['seconds']		= 'Seconds';
$lang['ago']			= 'ago';

// navigation path
$lang['root']			= 'Root';

// top message
$lang['message']		= '<p>Welcome to the CVS Repository viewing system for the phpCVSView project hosted at SourceForge.net</p><p>The goal of this project is simply to build a php application/class to provide access to a CVS based source control repository over the various connectivity mechanisms available for CVS in general. There are also some extensions to this goal planned for future releases such as a full web-based CVS client utilising the core of this project.</p><p>So please feel free to look at our code, suggest features, test the code in your own environment, submit bugs, and most of all support the commitment of the open source developers by using the many wonderful products available.</p><p>Kindest Regards,<br />Brian Cheeseman. <br />phpCVSView Project Leader.</p>';

// bottom messages
$lang['generated']		= 'This page was generated by <a href="http://phpcvsview.sourceforge.net/">phpCVSView</a> in ';
$lang['created_by']		= 'phpCVSView created by <a href="mailto:bcheesem@users.sourceforge.net">Brian Cheeseman</a> and <a href="mailto:sijis@users.sourceforge.net">Sijis Aviles</a>.';

// file options
$lang['view']			= 'view';
$lang['download']		= 'download';
$lang['diff']			= 'diff to previous';
$lang['annotate']		= 'annotate';

// file details
$lang['revision']		= 'Revision';
$lang['last_checkin']	= 'Last Checkin:';
$lang['notice']			= 'Notice:';
$lang['branch']			= 'Branch:';
$lang['date']			= 'Date:';
$lang['time']			= 'Time:';
$lang['state']			= 'State:';
$lang['changes']		= 'Changes since ';
$lang['log_message']	= 'Log Message:';

// error messages
$lang['err_connect']	= '<h2>ERROR: Could not connect to the PServer.</h2>'."\n";

?>
